CREATE TABLE IF NOT EXISTS users ( 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	email varchar NOT NULL UNIQUE, 
	name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
	item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	name varchar NOT NULL,
	description varchar NOT NULL,
	available boolean NOT NULL,
	owner_id BIGINT REFERENCES users (user_id)
);